-- Generated by SQL Maestro for MySQL Professional. Release date 09/05/2012
-- 14/11/2013 05:26:08 p.m.
-- ----------------------------------
-- Alias: elearning at localhost
-- Database name: elearning
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.5.24
-- Session ID: 8
-- Character set: latin1
-- Collation: latin1_swedish_ci


CREATE DATABASE elearning
  CHARACTER SET latin1
  COLLATE latin1_swedish_ci;

USE elearning;

/* Tables */
CREATE TABLE archivos (
  id              int AUTO_INCREMENT NOT NULL,
  created         datetime,
  modified        datetime,
  nombre          varchar(100),
  tipo_documento  int(1) NOT NULL,
  estado          int(1) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE participantes (
  id                 int AUTO_INCREMENT NOT NULL,
  created            datetime,
  modified           datetime,
  nombre             varchar(200) NOT NULL,
  iniciales          varchar(10) NOT NULL,
  tipo_participante  int(1) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE preguntas (
  id               int AUTO_INCREMENT NOT NULL,
  created          datetime,
  modified         datetime,
  texto            varchar(200) NOT NULL,
  opcion_correcta  int(3) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE respuestas (
  id                   int AUTO_INCREMENT NOT NULL,
  created              datetime,
  modified             datetime,
  pregunta_id          int NOT NULL,
  participante_id      int NOT NULL,
  opcion_participante  int(3) NOT NULL,
  calificacion         int(1) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE usuarios (
  id        int AUTO_INCREMENT NOT NULL,
  created   datetime,
  modified  datetime,
  username  varchar(50) NOT NULL,
  password  varchar(20) NOT NULL,
  grupo     int(1) NOT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB;

/* Indexes */
CREATE INDEX fk_respuestas_participantes
  ON respuestas
  (participante_id);

CREATE INDEX fk_respuestas_preguntas
  ON respuestas
  (pregunta_id);

/* Foreign Keys */
ALTER TABLE respuestas
  ADD CONSTRAINT fk_respuestas_participantes
  FOREIGN KEY (participante_id)
    REFERENCES participantes(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE respuestas
  ADD CONSTRAINT fk_respuestas_preguntas
  FOREIGN KEY (pregunta_id)
    REFERENCES preguntas(id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

/* Data for table "archivos" */


/* Data for table "participantes" */
INSERT INTO participantes (id, created, modified, nombre, iniciales, tipo_participante) VALUES
  (2, '2013-11-13 15:53:42', '2013-11-13 15:53:42', 'ALLIEVI Gustavo Enrique', 'GUEA', 2),
  (3, '2013-11-13 17:45:00', '2013-11-13 17:45:00', 'tt', 'tt', 2);


/* Data for table "preguntas" */
INSERT INTO preguntas (id, created, modified, texto, opcion_correcta) VALUES
  (1, '2013-11-14 10:49:49', '2013-11-14 10:49:53', 'El 3P es', 3),
  (2, '2013-11-14 10:50:27', '2013-11-14 10:50:30', 'El IDP es', 1),
  (3, '2013-11-14 10:50:56', '2013-11-14 10:50:59', 'El 3P tiene', 3),
  (4, '2013-11-14 10:51:25', '2013-11-14 10:51:28', 'Un perfil competencial es:', 2),
  (5, '2013-11-14 10:52:00', '2013-11-14 10:52:03', 'Los niveles de competencia para fuerza de ventas son:', 3),
  (6, '2013-11-14 10:52:26', '2013-11-14 10:52:29', 'Dentro de los criterios de progresión, para la promoción de un representante de ventas se debe tener en cuenta como requisito mandatorio:', 4),
  (7, '2013-11-14 10:53:52', '2013-11-14 10:53:55', 'Para pasar de Rep a Rep Senior es necesario:', 5),
  (8, '2013-11-14 10:54:12', '2013-11-14 10:54:15', 'Porque tenemos un diccionario de competencias? ', 2),
  (9, '2013-11-14 10:54:39', '2013-11-14 10:54:43', 'Quienes están contemplados en este diccionario?', 3),
  (10, '2013-11-14 10:55:15', '2013-11-14 10:55:18', 'Que competencia contempla la ética empresarial?', 2),
  (11, '2013-11-14 10:55:39', '2013-11-14 10:55:42', 'Cuantas de las competencias son aplicables a una persona?', 2),
  (12, '2013-11-14 10:56:59', '2013-11-14 10:57:02', 'Que es un descriptor?', 2),
  (13, '2013-11-14 10:58:07', '2013-11-14 10:58:10', 'A que competencia corresponde el descriptor  “ofrece soluciones y mensajes claves a los clientes”', 1);


/* Data for table "respuestas" */


/* Data for table "usuarios" */
INSERT INTO usuarios (id, created, modified, username, password, grupo) VALUES
  (2, '2013-11-13 15:28:30', '2013-11-13 15:29:18', 'admin', 'admin', 1);
